spring:
  application.name: service-turbine
server:
  port: 7112
turbine:
  aggregator:
    clusterConfig: CONSUMER # 指定Culster
  appConfig: SERVICE-CONSUMER
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/,http://eureka2:1112/eureka/