server:
  port: 4111
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/doulala1986/micro-service-springcloud
          search-paths: ConfigStore
          username: sodoulala@163.com
          password: samsara86
  rabbitmq:
    host: localhost
    port: 6111
    username: user
    password: password
endpoints:
  restart:
    enabled: true

eureka:
  client:
      serviceUrl:
        defaultZone: http://eureka2:1112/eureka/