server:
  port: 3111

eureka:
  instance:
    appname: service-consumer
    leaseRenewalIntervalInSeconds: 30 #default 30 seconds
    leaseExpirationDurationInSeconds: 60 # default 90 seconds
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/,http://eureka2:1112/eureka/


#serviceprovider:
ribbon:
    ServerListRefreshInterval: 60000 #刷新时间
    ReadTimeout: 5000 #timeout
    MaxAutoRetries: 2 #重试次数
    MaxAutoRetriesNextServer: 1 #重试实例的个数
    ActiveConnectionsLimit: 200 #链接数上限
    OkToRetryOnAllOperations: true #开启失败重试机制
spring:
  zipkin:
    base-url: http://localhost:8111
    compression:
      enabled: false
    flush-interval: 1

