---
spring:
  profiles: eureka1                                 # 指定profile=eureka1
server:
  port: 1111
eureka:
  instance:
    hostname: eureka1                               # 指定当profile=eureka1，主机名
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka2:1112/eureka/      # 将自己注册到eureka2这个Eureka上面去
---
spring:
  profiles: eureka2
server:
  port: 1112
eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/